### ISSUE TITLE
Create build system

### ISSUE THREAD

**Issue by splict** [nblenke/galactic-endeavor#9]
I think my project access is read only, so I couldn't convert the TODO.

Started working in build-system-wip. Currently it only renders properly after triggering a rebuild by saving a file.

Directions:

```js
yarn install
yarn start
```

Go to http://localhost:5000

TODO:

- Get working without needing a rebuild
- Switch from including JS to using npm modules
- Use imports instead of global references and iifes
- more...

**Comment by nblenke** [comment]
This looks promising: https://github.com/lean/phaser-es6-webpack

**Comment by nblenke** [comment]
Moved to use create-react-app. Thanks for the effort bro!
